#!/usr/bin/env python3
"""Generate src/bank_data.asm: deterministic per-8KiB-bank signatures.

Emits one pair of fixed-address ROMX sections per RGBDS 16 KiB bank
(1..RGBDS_BANK_COUNT-1), each holding the 16-byte signature for one of
the two MBC6 8 KiB physical sub-banks it contains, at local offset
SIG_LOCAL_OFFSET ($1FF0). Physical banks 0 and 1 live in the fixed
bank 0 and are emitted by src/header.asm instead (see comment there),
since bank 0 also carries the cartridge header and startup code.

This file is generated, not hand-edited. Layout constants are shared
with tools/verify_rom.py via mbc6_layout.py so the two can't drift.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from mbc6_layout import (
    RGBDS_BANK_COUNT,
    RGBDS_BANK_SIZE,
    SIG_LOCAL_OFFSET,
    signature_bytes,
)

HEADER = """\
; Generated by tools/gen_bank_data.py — do not hand-edit.
; 8 KiB physical bank signatures for RGBDS banks 1..{last} (physical
; MBC6 banks 2..{maxbank}). Physical banks 0/1 are emitted in src/header.asm.
; See CLAUDE.md "ROM bank layout" and tools/mbc6_layout.py for the format.

""".format(last=RGBDS_BANK_COUNT - 1, maxbank=2 * RGBDS_BANK_COUNT - 1)

A_WINDOW_ADDR = 0x4000 + SIG_LOCAL_OFFSET  # $5FF0
B_WINDOW_ADDR = 0x6000 + SIG_LOCAL_OFFSET  # $7FF0


def db_line(data: bytes) -> str:
    return "    db " + ", ".join(f"${b:02X}" for b in data)


def emit_bank(rgbds_bank: int) -> str:
    phys_a = 2 * rgbds_bank
    phys_b = 2 * rgbds_bank + 1
    sig_a = signature_bytes(phys_a)
    sig_b = signature_bytes(phys_b)
    lines = []
    lines.append(f"SECTION \"BankSig_{phys_a:03d}\", ROMX[${A_WINDOW_ADDR:04X}], BANK[{rgbds_bank}]")
    lines.append(db_line(sig_a))
    lines.append("")
    lines.append(f"SECTION \"BankSig_{phys_b:03d}\", ROMX[${B_WINDOW_ADDR:04X}], BANK[{rgbds_bank}]")
    lines.append(db_line(sig_b))
    lines.append("")
    return "\n".join(lines)


def emit_fixed_bank_signatures() -> str:
    """Physical banks 0 and 1 live in the fixed RGBDS bank 0 (ROM0),
    alongside the header and startup code, so they get plain ROM0
    sections at fixed CPU addresses instead of a BANK[n] ROMX section."""
    sig0 = signature_bytes(0)
    sig1 = signature_bytes(1)
    lines = [
        "; Generated by tools/gen_bank_data.py — do not hand-edit.",
        "; Physical bank 0/1 signatures; included by src/header.asm.",
        "",
        f"SECTION \"BankSig_000\", ROM0[${SIG_LOCAL_OFFSET:04X}]",
        db_line(sig0),
        "",
        f"SECTION \"BankSig_001\", ROM0[${0x2000 + SIG_LOCAL_OFFSET:04X}]",
        db_line(sig1),
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    src_dir = Path(__file__).parent.parent / "src"

    out_path = src_dir / "bank_data.asm"
    parts = [HEADER]
    for rgbds_bank in range(1, RGBDS_BANK_COUNT):
        parts.append(emit_bank(rgbds_bank))
    out_path.write_text("\n".join(parts))
    print(f"wrote {out_path} ({RGBDS_BANK_COUNT - 1} banks x 2 signatures)")

    fixed_path = src_dir / "bank_data_fixed.asm"
    fixed_path.write_text(emit_fixed_bank_signatures())
    print(f"wrote {fixed_path} (banks 0-1)")


if __name__ == "__main__":
    main()
