#!/usr/bin/env python3
"""Generate src/build_info.asm: a short build identifier shown on every
screen of the UI, so a bug report can be tied to an exact commit.

Unlike the other generated sources, this is NOT cached/skipped when
already present — the Makefile always re-runs this, since the git HEAD
can change between builds even when no tracked source file does.
"""
import subprocess
from pathlib import Path


def get_build_id() -> str:
    try:
        sha = subprocess.run(
            ["git", "rev-parse", "--short=7", "HEAD"],
            capture_output=True, text=True, check=True, timeout=5,
        ).stdout.strip().upper()
    except Exception:
        return "UNKNOWN"

    try:
        dirty = subprocess.run(
            ["git", "status", "--porcelain"],
            capture_output=True, text=True, check=True, timeout=5,
        ).stdout.strip()
    except Exception:
        dirty = ""

    build_id = sha if sha else "UNKNOWN"
    if dirty:
        build_id += "+"  # uncommitted changes present at build time
    return build_id[:8]  # font only needs to fit "XXXXXXX+"


def main() -> None:
    build_id = get_build_id()
    lines = [
        "; Generated by tools/gen_build_info.py — do not hand-edit.",
        "; Not cached like the other generated sources: the Makefile",
        "; always re-runs this generator, since the git commit can",
        "; change without any tracked source file changing.",
        "",
        "SECTION \"Build Info\", ROM0",
        "",
        "BuildIDText::",
        f"    db \"{build_id}\", 0",
    ]
    out_path = Path(__file__).parent.parent / "src" / "build_info.asm"
    out_path.write_text("\n".join(lines) + "\n")
    print(f"wrote {out_path} (build id: {build_id})")


if __name__ == "__main__":
    main()
