; Cartridge header for the MBC6 test ROM.
;
; Only the bytes rgbfix cannot populate from CLI flags are written here
; (RST/interrupt vectors, entry point, and zeroed placeholders for the
; header fields the Makefile's `rgbfix` invocation fills in: Nintendo
; logo, title, CGB flag, licensee, cartridge type, ROM/RAM size,
; checksums). See CLAUDE.md "Required ROM format" and Pan Docs
; "The Cartridge Header" (https://gbdev.io/pandocs/The_Cartridge_Header.html).
;
; Physical 8 KiB bank signatures for banks 0 and 1 (which live in this
; fixed bank) are emitted at the end of this file, at local offset
; $1FF0/$3FF0 exactly like every other bank — see tools/mbc6_layout.py.

; ---- RST vectors: unused by this ROM, stubbed defensively ----
SECTION "RST00", ROM0[$00]
    ret
SECTION "RST08", ROM0[$08]
    ret
SECTION "RST10", ROM0[$10]
    ret
SECTION "RST18", ROM0[$18]
    ret
SECTION "RST20", ROM0[$20]
    ret
SECTION "RST28", ROM0[$28]
    ret
SECTION "RST30", ROM0[$30]
    ret
SECTION "RST38", ROM0[$38]
    ret

; ---- Interrupt vectors: this ROM polls hardware state, it does not
; rely on interrupts, but IE is left at 0 so these are defensive stubs
; only in case a stray interrupt fires. ----
SECTION "Int VBlank", ROM0[$40]
    reti
SECTION "Int STAT", ROM0[$48]
    reti
SECTION "Int Timer", ROM0[$50]
    reti
SECTION "Int Serial", ROM0[$58]
    reti
SECTION "Int Joypad", ROM0[$60]
    reti

; ---- Entry point ----
; Start is defined in main.asm and exported with EXPORT; rgbasm
; imports unknown symbols automatically at link time.
SECTION "Entry Point", ROM0[$100]
    nop
    jp Start

; ---- Nintendo logo: zeroed placeholder, patched by `rgbfix -v` (fix
; spec "l") at build time so the required boot logo bytes are not
; hand-copied into this source tree. ----
SECTION "Nintendo Logo", ROM0[$104]
    ds $133 - $104 + 1, 0

; ---- Title / manufacturer code / CGB flag: patched by `rgbfix -t -C` ----
SECTION "Title", ROM0[$134]
    ds $143 - $134 + 1, 0

; ---- New licensee code: patched by `rgbfix -k` ----
SECTION "New Licensee", ROM0[$144]
    ds $145 - $144 + 1, 0

; ---- SGB flag: not set (SGB is out of scope; CGB-only target) ----
SECTION "SGB Flag", ROM0[$146]
    db $00

; ---- Cartridge type: patched by `rgbfix -m MBC6` -> $20 ----
SECTION "Cart Type", ROM0[$147]
    db $00

; ---- ROM size: patched by `rgbfix -p` (auto-sized to the linked image) -> $05 ----
SECTION "ROM Size", ROM0[$148]
    db $00

; ---- RAM size: patched by `rgbfix -r $03` ----
SECTION "RAM Size", ROM0[$149]
    db $00

; ---- Destination code: patched by `rgbfix -j` (non-Japanese) ----
SECTION "Destination Code", ROM0[$14A]
    db $00

; ---- Old licensee code: patched by `rgbfix -l $33` ----
SECTION "Old Licensee", ROM0[$14B]
    db $00

; ---- Mask ROM version: patched by `rgbfix -n $00` ----
SECTION "Mask ROM Version", ROM0[$14C]
    db $00

; ---- Header checksum / global checksum: patched by `rgbfix -v` ----
SECTION "Header Checksum", ROM0[$14D]
    db $00
SECTION "Global Checksum", ROM0[$14E]
    ds 2, 0

; Physical 8 KiB bank signatures for banks 0 and 1 (the two sub-banks
; that live in this fixed bank) are generated by tools/gen_bank_data.py
; as the standalone source file src/bank_data_fixed.asm (built and
; linked like any other src/*.asm file — see Makefile), at local
; offset $1FF0/$3FF0 exactly like every other bank; see
; tools/mbc6_layout.py. Bank 0's signature at CPU address $1FF0 is
; well past the header ($14F) and past all code placed by main.asm et
; al (kept short per CLAUDE.md's "Fixed-ROM safety rule").
